//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamersOperzalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camers_operzal_configuration
    {
        public string config_id { get; set; }
        public string config_value { get; set; }
        public string config_description { get; set; }
    }
}
