//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamersOperzalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class camers_operzal_ifns
    {
        public camers_operzal_ifns()
        {
            this.camers_operzal_general = new HashSet<camers_operzal_general>();
        }
    
        [Required]
        public string ifns_cod { get; set; }
        [Required]
        public string ifns_name { get; set; }
        public Nullable<int> order { get; set; }
    
        public virtual ICollection<camers_operzal_general> camers_operzal_general { get; set; }
    }
}
