//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamersOperzalAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camers_operzal_general
    {
        public int id { get; set; }
        public string ifns_code { get; set; }
        public string camera_img_link { get; set; }
        public string camera_img_file { get; set; }
        public Nullable<int> camera_disable { get; set; }
        public string camera_disable_description { get; set; }
        public string camera_user { get; set; }
        public string camera_password { get; set; }
    
        public virtual camers_operzal_ifns camers_operzal_ifns { get; set; }
    }
}
